<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <SignAssembly>False</SignAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <NeutralLanguage>ru</NeutralLanguage>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Acly Main Library</Title>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>acly</PackageTags>
    <Version>1.14.6</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Laeslaraftor/Acly</RepositoryUrl>
    <Authors>Laeslaraftor</Authors>
    <PackageIcon>Icon.png</PackageIcon>
    <Description>Библиотека со всякими приколюхами</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
